### ISSUE TITLE
Handbrake file input limited to only mkv or m4v

### ISSUE THREAD

**Issue by Light-Wizzard** [yanfali/gomkv#11]
On line 144 of main this limits the input filepath.Glob(defaults.SrcDir + "/*.m[k4]v"), Handbrake supports many file types, not sure of all of them, maybe: mkv, m4v, mp4, mpg, mpeg, avi, ts, m2ts, wmv, rm, asf, qt, mxf, vpx8, flv, webm, mov, m4a, 3gp, 3g2, mj2, I have not tried all of them, but you need to add more to make the program useful, also you might want to make it case insensitive.

**Comment by yanfali** [comment]
fixed
